### ISSUE TITLE
MechWarrior 5 Release 4.26-CL-0, GOG SDK Ver. 1.139.2

### ISSUE THREAD

**Issue by OddPrograms** [grasmanek94/UniverseLAN#4]
- Launches but states offline
- Attempting to click Coop states not connected to online services

**Comment by OddPrograms** [comment]
I've attempted doing the interceptor test for MechWarrior 5 but the issue is I'm unable to test creating a lobby, as soon as I hit CO-OP is throws the not connected error, and doesn't generate any interceptor/tracing logs.

**Comment by Artipep** [comment]
The same problem as the user OddPrograms, MechWarrior 5: Mercenaries game version 1.1.361. The game starts, but in the game it says offline mode and when you press the co-op button it says: failed to login to online services.

**Comment by grasmanek94** [comment]
```
+universelan::client::UserImpl::RequestEncryptedAppTicket@7fffcf629e62
 data: 0x0
 dataSize: 0
 listener: 0x1cc1b97cfb0
-universelan::client::UserImpl::RequestEncryptedAppTicket@7fffcf629e62
+universelan::client::EncryptedAppTicketListener::OnEncryptedAppTicketRetrieveSuccess@7fffcf629e62
-universelan::client::EncryptedAppTicketListener::OnEncryptedAppTicketRetrieveSuccess@7fffcf629e62
+universelan::client::EncryptedAppTicketListener::OnEncryptedAppTicketRetrieveSuccess@7fffcf629e62
 listener: 0x1cc1b97cfb0
 +universelan::client::UserImpl::GetEncryptedAppTicket@7fffcf629e62
  encryptedAppTicket: 0xbdf837dba0
  maxEncryptedAppTicketSize: 1024
  currentEncryptedAppTicketSize: 289
 -universelan::client::UserImpl::GetEncryptedAppTicket@7fffcf629e62
-universelan::client::EncryptedAppTicketListener::OnEncryptedAppTicketRetrieveSuccess@7fffcf629e62
```
It seems MechWarrior 5 relies on Epic Online Services or Steam unfortunately :(
