### ISSUE TITLE
Gloomhaven "Host Session" Does not respond with Invite Code

### ISSUE THREAD

**Issue by Limb** [grasmanek94/UniverseLAN#6]
UniverseLAN Version: 1.148.3-487
Gloomhaven Version: GOG 1.1.8307

Created a new campaign in Gloomhaven, but when I try to host a multiplayer session, the "Host Session" button visible responds to the click, but does not change to the screen showing the invite code to give to other players. No output actions are logged in either the client or server windows when the button is pressed.

Additionally I noticed that before clicking the "Host session" button, there is no indicator next to the "Multiplayer" button on the escape menu. However after clicking the "Host Session" button and closing/reopening the menu, there is a green indicator next to the "Multiplayer" menu. Trying to host a session after this green button appears has no change.

I'm not sure what version of Gloomhaven was tested when the game was added to the compatibility list, is it possible a update was made to the game that broke multiplayer functionality with UniverseLAN?

**Comment by grasmanek94** [comment]
https://github.com/user-attachments/assets/e190700d-eba7-48c5-ac5b-e4372e778e20

The version tested was 1.1.8307.0.

If it doesn't work anymore then some version has broken it and will require some investigation. It's unclear what this game uses for communication, but that version does work through UniverseLAN (although I can't find any calls to Create/Join lobby in the Tracing directories from the normal logs, maybe this would require the call logger component to be used for extra fine logging).

**Comment by Limb** [comment]
Looks like this is related to a firewall blocking issue on my specific network. I'm guessing Gloomhaven does something outside of the GOG library to create/request the share code. I was able to get Multiplayer working fine by using a different network.

Thank you for the support!
