### ISSUE TITLE
MechWarrior 5: Mercenaries, game version 1.1.361, GOG SDK 1.139.2

### ISSUE THREAD

**Issue by Artipep** [grasmanek94/UniverseLAN#7]
Hello. The same problem as the user OddPrograms, MechWarrior 5: Mercenaries game version 1.1.361. The game starts, but in the game it says offline mode and when you press the co-op button it says: failed to login to online services.

**Comment by Artipep** [comment]
After some testing and using other emulators, I found out that when I press the co-op button, the game makes a call to GetEncryptedAppTicket, and if nothing is returned, the game writes that it was not possible to connect to online services. Some people said that the game may use an authorization server, which makes it impossible to use the emulator to play on a local network.

**Comment by grasmanek94** [comment]
Ah, if it makes a call to encrypted app ticket then it probably relies on some other service like Steam, Epic Online Services (EOS), XBOX live etc.. :( There's not much to do in such a case (unless there are some options in the game to not use those services).

Usually GOG generates a 'ticket' for the game, which it receives, and then with that ticket the game can connect to the 'real' multiplayer service.

For Steam there already exist alternatives that allow LAN play.
As for EOS that would be a future project maybe in a few years - if no one else beats me to it.

**Comment by grasmanek94** [comment]
Yes I confirmed today the MechWarrior 5 series doesn't use GOG Galaxy for Multiplayer unfortunately. That's a bummer. Maybe I should make a EOS extension to emulate LAN functionality there too (but that will be a project that won't be finished in a year or two with my free time).
